version: '1.0'
volumes:
  node_modules:
services:
  dvb-i-tools:
    build: .
    environment:
      - no_proxy=localhost,127.0.0.1
    volumes:
      - "${GIT_CLONE_PATH:-./}:/usr/src/app"
      - node_modules:/usr/src/app/node_modules
    ports:
      - "3030:3030"