
export const tva = {

	SYNOPSIS_BRIEF_LABEL: "brief",
	SYNOPSIS_BRIEF_LENGTH: 30,
	SYNOPSIS_SHORT_LABEL: "short",
	SYNOPSIS_SHORT_LENGTH: 90,
    SYNOPSIS_MEDIUM_LABEL: "medium", 
    SYNOPSIS_MEDIUM_LENGTH: 250, 
    SYNOPSIS_LONG_LABEL: "long",
	SYNOPSIS_LONG_LENGTH: 1200, 
	SYNOPSIS_EXTENDED_LABEL: "extended",

	KEYWORD_TYPE_MAIN: "main",
	KEYWORD_TYPE_SECONDARY: "secondary",
	KEYWORD_TYPE_OTHER: "other",
	DEFAULT_KEYWORD_TYPE: "main",

	GENRE_TYPE_MAIN: "main",
	GENRE_TYPE_SECONDARY: "secondary",
	GENRE_TYPE_OTHER: "other",
	DEFAULT_GENRE_TYPE: "main",
	ALL_GENRE_TYPES: ["main", "secondary", "other"],

	DELIVERY_MODE_STREAMING: "streaming",

	SCAN_TYPES: 	["interlaced", "progressive"],
	COLOR_TYPES: 	["color", "blackAndWhite", "blackAndWhiteAndColor", "colorized"],
	
	ALLOWED_ASPECT_RATIO_TYPES: ["original", "publication"],

	e_TVAMain: 			"TVAMain",
	e_ProgramInformationTable: "ProgramInformationTable",
	e_ProgramLocationTable: "ProgramLocationTable",
	e_GroupInformationTable: "GroupInformationTable",

	e_ActualStartTime: 	"ActualStartTime",
	e_AspectRatio: 		"AspectRatio",
	e_AVAttributes: 		"AVAttributes",
	e_AudioAttributes: 	"AudioAttributes", 
	e_AudioLanguage: 	"AudioLanguage",
	e_AuxiliaryURI: 		"AuxiliaryURI",
	e_AuxiliaryURL: 		"AuxiliaryURL",
	e_BasicDescription: 	"BasicDescription",
	e_BitRate: 			"BitRate",
	e_BitsPerSample:    "BitsPerSample", 
	e_CaptioningAttributes: "CaptioningAttributes",	
	e_CaptionLanguage: 	"CaptionLanguage",
	e_Character: 		"Character",
	e_Coding: 			"Coding",
	e_Color: 			"Color", 
	e_CreditsItem: 		"CreditsItem",
	e_CreditsList: 		"CreditsList",
	e_DeliveryMode: 		"DeliveryMode",
	e_EndOfAvailability: "EndOfAvailability",
	e_EpisodeOf: 		"EpisodeOf",
	e_ExplanatoryText: 	"ExplanatoryText",
	e_FamilyName: 		"FamilyName",
	e_FirstShowing: 		"FirstShowing",
	e_Format: 			"Format",
	e_FrameRate: 		"FrameRate",
	e_Free: 				"Free",
	e_Genre: 			"Genre",
	e_GivenName: 		"GivenName",
	e_GroupInformation: 	"GroupInformation",
	e_GroupType: 		"GroupType",
	e_HorizontalSize: 	"HorizontalSize", 
	e_HowRelated: 		"HowRelated",
	e_InstanceDescription: "InstanceDescription",
	e_Keyword: 			"Keyword",
	e_MediaLocator: 		"MediaLocator",
	e_MediaUri: 			"MediaUri",
	e_MemberOf: 			"MemberOf",
	e_MinimumAge: 		"MinimumAge",
	e_MixType: 			"MixType",
	e_NumOfChannels: 	"NumOfChannels", 
	e_OnDemandProgram: 	"OnDemandProgram",
	e_OrganizationName: 	"OrganizationName",
	e_OtherIdentifier: 	"OtherIdentifier",
	e_ParentalGuidance: 	"ParentalGuidance",
	e_ParentalRating: 	"ParentalRating",
	e_PersonName: 		"PersonName",
	e_PictureFormat: 	"PictureFormat", 
	e_ProgramDescription: "ProgramDescription",
	e_ProgramInformation: "ProgramInformation",
	e_Program: 			"Program",
	e_ProgramURL: 		"ProgramURL",
	e_PublishedDuration: "PublishedDuration",
	e_PublishedStartTime: "PublishedStartTime",
	e_RelatedMaterial: 	"RelatedMaterial",
	e_SampleFrequency:  "SampleFrequency",
	e_Scan: 				"Scan", 
	e_Schedule: 			"Schedule",
	e_ScheduleEvent: 	"ScheduleEvent",
	e_SignLanguage: 		"SignLanguage",
	e_StartOfAvailability: "StartOfAvailability",
	e_StillPictureFormat: "StillPictureFormat",
	e_Synopsis: 			"Synopsis",
	e_Title: 			"Title",
	e_VerticalSize: 		"VerticalSize", 
	e_VideoAttributes: 	"VideoAttributes", 
	
	a_average: 			"average",
	a_closed: 			"closed",
	a_contentType: 		"contentType",
	a_crid: 				"crid",
	a_end: 				"end",
	a_groupId: 			"groupId",
	a_horizontalSize: 	"horizontalSize",
	a_href: 				"href",
	a_index: 			"index",
	a_lang: 				"lang",
	a_length: 			"length",
	a_maximum: 			"maximum",
	a_minimum: 			"minimum",
	a_numOfItems: 		"numOfItems",
	a_ordered: 			"ordered",
	a_primary: 			"primary",
	a_programId: 		"programId",
	a_purpose: 			"purpose",
	a_role: 				"role",
	a_serviceIDRef: 		"serviceIDRef",
	a_start: 			"start",
	a_supplemental: 		"supplemental",
	a_translation: 		"translation",
	a_type: 				"type",
	a_uriType: 			"uriType",
	a_variable: 			"variable",
	a_value: 			"value",
	a_verticalSize: 		"verticalSize",

	v_lengthLong: 		"long",
	
	t_MemberOfType: 		"MemberOfType",
	t_ProgramGroupTypeType: "ProgramGroupTypeType",
	
	cs_PromotionalStillImage: "urn:tva:metadata:cs:HowRelatedCS:2012:19"
};